# Generated by Django 5.2.7 on 2025-10-08 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_vehicle_accident_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 17-character VIN (excluding I, O, and Q).', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard License Plate'), ('personalized', 'Personalized License Plate (Wunschkennzeichen)'), ('seasonal', 'Seasonal License Plate (Saisonkennzeichen)'), ('red', 'Red License Plate (Rote Kennzeichen) - Trade/Test'), ('green', 'Green License Plate (Grüne Kennzeichen) - Agricultural'), ('yellow', 'Yellow License Plate (Gelbe Kennzeichen) - Military'), ('diplomatic', 'Diplomatic License Plate'), ('export', 'Export License Plate'), ('temporary', 'Temporary License Plate (Kurzzeitkennzeichen)'), ('classic', 'Classic Car License Plate (H-Kennzeichen)'), ('electric', 'Electric Vehicle License Plate (E-Kennzeichen)'), ('disabled', 'Disabled Person License Plate'), ('taxi', 'Taxi License Plate'), ('police', 'Police License Plate'), ('ambulance', 'Emergency Vehicle License Plate'), ('fire_department', 'Fire Department License Plate'), ('government', 'Government Vehicle License Plate'), ('municipal', 'Municipal Vehicle License Plate'), ('eu_standard', 'EU Standard License Plate'), ('international', 'International License Plate'), ('transit', 'Transit License Plate'), ('foreign', 'Foreign License Plate'), ('other', 'Other License Plate Type')], help_text='Type of official license plate (Amtliches Kennzeichen)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='motor_vehicle_registration_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid German vehicle registration number (5-15 characters, letters, numbers, hyphens, spaces).', regex='^[A-Z0-9\\-\\s]{5,15}$')]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='official_license_plate',
            field=models.CharField(blank=True, help_text='Official License Plate Number (Amtliches Kennzeichen) - Format: District-Letters Numbers (e.g., B-AB 1234)', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid German license plate (e.g., B-AB 1234).', regex='^[A-Z]{1,3}-[A-Z]{1,2} \\d{1,4}$')]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sale_invoice_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('in_preparation', 'In Preparation'), ('reserved', 'Reserved'), ('deposit_paid', 'Deposit Paid'), ('sold', 'Sold')], max_length=20, null=True),
        ),
    ]
