# Generated by Django 5.2.7 on 2025-10-08 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_vehicle_chassis_number_vehicle_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='official_license_plate',
            field=models.CharField(blank=True, help_text='Official License Plate Number (Amtliches Kennzeichen) - Format: District-Letters Numbers (e.g., B-AB 1234)', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid German license plate (e.g., B-AB 1234).', regex='^[A-Z]{1,3}-[A-Z]{1,2}\\d{1,4}$')]),
        ),
    ]
