# Generated by Django 5.2.7 on 2025-10-08 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_vehicle_official_license_plate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='license_plate',
        ),
    ]
