# Generated by Django 5.2.7 on 2025-10-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_vehicle_doors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='license_plate_type',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='motor_vehicle_registration_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='official_license_plate',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
