# Generated by Django 5.2.7 on 2025-10-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_remove_vehicle_license_plate_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manufacturer_model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
