# Generated by Django 5.2.7 on 2025-10-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_remove_vehicle_model_vehicle_manufacturer_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='sale_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_delivery_collection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_price_taxes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
