# Generated by Django 5.2.7 on 2025-10-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='doors',
            field=models.PositiveIntegerField(blank=True, choices=[('2', '2 Doors'), ('3', '3 Doors'), ('4', '4 Doors'), ('5', '5 Doors'), ('6', '6 Doors')], null=True),
        ),
    ]
