# Generated by Django 5.2.7 on 2025-10-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_alter_vehicle_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/vehicles/'),
        ),
    ]
