# Generated by Django 5.2.7 on 2025-10-13 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_vehicle_is_active_alter_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 17-character VIN (excluding I, O, and Q).', regex='^[A-HJ-NPR-Z0-9]{17}$')]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='motor_vehicle_registration_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='official_license_plate',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_invoice_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
