# Generated by Django 5.2.7 on 2025-10-13 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_vehicle_chassis_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('vehicle_created', 'Vehicle Created'), ('vehicle_updated', 'Vehicle Updated'), ('vehicle_deleted', 'Vehicle Deleted'), ('vehicle_sold', 'Vehicle Sold'), ('vehicle_status_changed', 'Vehicle Status Changed'), ('user_created', 'User Created'), ('user_updated', 'User Updated'), ('user_deleted', 'User Deleted'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_password_changed', 'User Password Changed'), ('business_updated', 'Business Updated'), ('branch_created', 'Branch Created'), ('branch_updated', 'Branch Updated'), ('branch_deleted', 'Branch Deleted'), ('settings_updated', 'Settings Updated'), ('data_exported', 'Data Exported'), ('data_imported', 'Data Imported')], max_length=50)),
                ('description', models.TextField()),
                ('object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='manager.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['business', '-timestamp'], name='manager_act_busines_8b53fe_idx'), models.Index(fields=['user', '-timestamp'], name='manager_act_user_id_472d30_idx'), models.Index(fields=['action', '-timestamp'], name='manager_act_action_c4620a_idx')],
            },
        ),
    ]
