# Generated by Django 5.2.7 on 2025-10-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('in_preparation', 'In Preparation'), ('reserved', 'Reserved'), ('deposit_paid', 'Deposit Paid'), ('sold', 'Sold'), ('inactive', 'Inactive')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
