# Generated by Django 5.2.7 on 2025-10-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_alter_vehicle_status_delete_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('purchased', 'Purchased'), ('ready_for_sale', 'Ready for Sale'), ('sold', 'Sold'), ('inactive', 'Inactive')], max_length=20, null=True),
        ),
    ]
