# Generated by Django 5.2.7 on 2025-10-14 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_alter_vehicle_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_active',
        ),
    ]
