# Generated by Django 5.2.7 on 2025-10-14 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0021_person_vehicle_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_vehicles', to='manager.person'),
        ),
    ]
