# Generated by Django 5.2.7 on 2025-10-16 17:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_vehicle_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='manager.business', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='manager.business', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='manager.business', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='is manager'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='accident_vehicle',
            field=models.BooleanField(blank=True, null=True, verbose_name='accident vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('compact', 'Compact'), ('mid_size', 'Mid-Size'), ('full_size', 'Full-Size'), ('subcompact', 'Subcompact'), ('luxury', 'Luxury'), ('sports', 'Sports'), ('family', 'Family'), ('commercial', 'Commercial'), ('economy', 'Economy'), ('premium', 'Premium'), ('performance', 'Performance'), ('crossover', 'Crossover'), ('off_road', 'Off-Road'), ('city', 'City Car'), ('executive', 'Executive')], max_length=20, null=True, verbose_name='body type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='manager.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='manager.business', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='buy_date',
            field=models.DateField(blank=True, null=True, verbose_name='buy date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='buy_delivery_collection_date',
            field=models.DateField(blank=True, null=True, verbose_name='buy delivery/collection date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='buy_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('check', 'Check'), ('financing', 'Financing/Loan'), ('lease', 'Lease'), ('trade_in', 'Trade-in'), ('cryptocurrency', 'Cryptocurrency'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('samsung_pay', 'Samsung Pay'), ('venmo', 'Venmo'), ('zelle', 'Zelle'), ('wire_transfer', 'Wire Transfer'), ('money_order', 'Money Order'), ('cashiers_check', "Cashier's Check"), ('certified_check', 'Certified Check'), ('personal_check', 'Personal Check'), ('business_check', 'Business Check'), ('cash_equivalent', 'Cash Equivalent'), ('other', 'Other')], max_length=20, null=True, verbose_name='buy payment method'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='buy_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='buy price'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='buy_price_taxes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='buy price taxes'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bought_vehicles', to='manager.person', verbose_name='buyer'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 17-character VIN (excluding I, O, and Q).', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='chassis number (VIN)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('silver', 'Silver'), ('gray', 'Gray'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('brown', 'Brown'), ('beige', 'Beige'), ('gold', 'Gold'), ('purple', 'Purple'), ('pink', 'Pink'), ('other', 'Other')], max_length=20, null=True, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='doors',
            field=models.CharField(blank=True, choices=[('2', '2 Doors'), ('3', '3 Doors'), ('4', '4 Doors'), ('5', '5 Doors'), ('6', '6 Doors')], null=True, verbose_name='doors'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='first_registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='first registration date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('gasoline', 'Gasoline/Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('lpg', 'LPG (Liquid Petroleum Gas)'), ('cng', 'CNG (Compressed Natural Gas)'), ('ethanol', 'Ethanol'), ('hydrogen', 'Hydrogen')], max_length=20, null=True, verbose_name='fuel type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/vehicles/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='internal_comments',
            field=models.TextField(blank=True, null=True, verbose_name='internal comments'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='internal_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='internal id'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='kilometer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='kilometer'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('audi', 'Audi'), ('bmw', 'BMW'), ('mercedes', 'Mercedes-Benz'), ('porsche', 'Porsche'), ('volkswagen', 'Volkswagen'), ('opel', 'Opel'), ('mini', 'MINI'), ('smart', 'Smart'), ('maybach', 'Maybach'), ('bugatti', 'Bugatti'), ('lamborghini', 'Lamborghini'), ('bentley', 'Bentley'), ('rolls_royce', 'Rolls-Royce'), ('toyota', 'Toyota'), ('honda', 'Honda'), ('nissan', 'Nissan'), ('mazda', 'Mazda'), ('subaru', 'Subaru'), ('mitsubishi', 'Mitsubishi'), ('suzuki', 'Suzuki'), ('isuzu', 'Isuzu'), ('infiniti', 'Infiniti'), ('lexus', 'Lexus'), ('acura', 'Acura'), ('datsun', 'Datsun'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('cadillac', 'Cadillac'), ('buick', 'Buick'), ('gmc', 'GMC'), ('jeep', 'Jeep'), ('dodge', 'Dodge'), ('chrysler', 'Chrysler'), ('ram', 'RAM'), ('tesla', 'Tesla'), ('lincoln', 'Lincoln'), ('pontiac', 'Pontiac'), ('saturn', 'Saturn'), ('oldsmobile', 'Oldsmobile'), ('hummer', 'Hummer'), ('srt', 'SRT'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('genesis', 'Genesis'), ('ssangyong', 'SsangYong'), ('daewoo', 'Daewoo'), ('peugeot', 'Peugeot'), ('renault', 'Renault'), ('citroen', 'Citroën'), ('ds', 'DS'), ('alpine', 'Alpine'), ('fiat', 'Fiat'), ('alfa_romeo', 'Alfa Romeo'), ('lancia', 'Lancia'), ('ferrari', 'Ferrari'), ('maserati', 'Maserati'), ('pagani', 'Pagani'), ('jaguar', 'Jaguar'), ('land_rover', 'Land Rover'), ('range_rover', 'Range Rover'), ('aston_martin', 'Aston Martin'), ('mclaren', 'McLaren'), ('lotus', 'Lotus'), ('mg', 'MG'), ('triumph', 'Triumph'), ('rover', 'Rover'), ('jensen', 'Jensen'), ('volvo', 'Volvo'), ('saab', 'Saab'), ('koenigsegg', 'Koenigsegg'), ('skoda', 'Škoda'), ('seat', 'SEAT'), ('cupra', 'CUPRA'), ('geely', 'Geely'), ('byd', 'BYD'), ('great_wall', 'Great Wall'), ('chery', 'Chery'), ('jac', 'JAC'), ('dongfeng', 'Dongfeng'), ('saeic', 'SAIC'), ('lifan', 'Lifan'), ('haval', 'Haval'), ('wey', 'WEY'), ('lynk_co', 'Lynk & Co'), ('polestar', 'Polestar'), ('nio', 'NIO'), ('xpeng', 'XPeng'), ('li_auto', 'Li Auto'), ('hongqi', 'Hongqi'), ('tata', 'Tata'), ('mahindra', 'Mahindra'), ('maruti_suzuki', 'Maruti Suzuki'), ('bajaj', 'Bajaj'), ('hero', 'Hero'), ('tvs', 'TVS'), ('lada', 'Lada'), ('uaz', 'UAZ'), ('gaz', 'GAZ'), ('kamaz', 'KamAZ'), ('fiat_brazil', 'Fiat (Brazil)'), ('volkswagen_brazil', 'Volkswagen (Brazil)'), ('chevrolet_brazil', 'Chevrolet (Brazil)'), ('holden', 'Holden'), ('ford_australia', 'Ford (Australia)'), ('bombardier', 'Bombardier'), ('proton', 'Proton'), ('perodua', 'Perodua'), ('toyota_thailand', 'Toyota (Thailand)'), ('honda_thailand', 'Honda (Thailand)'), ('daihatsu', 'Daihatsu'), ('suzuki_indonesia', 'Suzuki (Indonesia)'), ('togg', 'TOGG'), ('ford_otosan', 'Ford Otosan'), ('ikco', 'IKCO'), ('saipa', 'Saipa'), ('nasr', 'Nasr'), ('el_nasr', 'El Nasr'), ('toyota_south_africa', 'Toyota (South Africa)'), ('ford_south_africa', 'Ford (South Africa)'), ('noble', 'Noble'), ('gumpert', 'Gumpert'), ('wiesmann', 'Wiesmann'), ('spyker', 'Spyker'), ('rimac', 'Rimac'), ('pininfarina', 'Pininfarina'), ('rivian', 'Rivian'), ('lucid', 'Lucid Motors'), ('fisker', 'Fisker'), ('freightliner', 'Freightliner'), ('peterbilt', 'Peterbilt'), ('kenworth', 'Kenworth'), ('mack', 'Mack'), ('volvo_trucks', 'Volvo Trucks'), ('scania', 'Scania'), ('man', 'MAN'), ('iveco', 'Iveco'), ('daf', 'DAF'), ('renault_trucks', 'Renault Trucks'), ('hino', 'Hino'), ('isuzu_trucks', 'Isuzu Trucks'), ('mitsubishi_fuso', 'Mitsubishi Fuso'), ('ud_trucks', 'UD Trucks'), ('tata_trucks', 'Tata Trucks'), ('ashok_leyland', 'Ashok Leyland'), ('eicher', 'Eicher'), ('bharatbenz', 'BharatBenz'), ('honda_motorcycles', 'Honda Motorcycles'), ('yamaha', 'Yamaha'), ('kawasaki', 'Kawasaki'), ('suzuki_motorcycles', 'Suzuki Motorcycles'), ('ducati', 'Ducati'), ('ktm', 'KTM'), ('husqvarna', 'Husqvarna'), ('bmw_motorcycles', 'BMW Motorcycles'), ('triumph_motorcycles', 'Triumph Motorcycles'), ('harley_davidson', 'Harley-Davidson'), ('indian', 'Indian'), ('victory', 'Victory'), ('aprilia', 'Aprilia'), ('mv_agusta', 'MV Agusta'), ('moto_guzzi', 'Moto Guzzi'), ('benelli', 'Benelli'), ('husaberg', 'Husaberg'), ('gas_gas', 'Gas Gas'), ('beta', 'Beta'), ('sherco', 'Sherco'), ('tm_racing', 'TM Racing'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=20, null=True, verbose_name='manufacturer'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer_model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='manufacturer model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='motor_vehicle_registration_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='motor vehicle registration number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='official_license_plate',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='official license plate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='power_kw',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='power (kW)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_date',
            field=models.DateField(blank=True, null=True, verbose_name='sale date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_delivery_collection_date',
            field=models.DateField(blank=True, null=True, verbose_name='sale delivery/collection date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_invoice_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='sale invoice number'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('check', 'Check'), ('financing', 'Financing/Loan'), ('lease', 'Lease'), ('trade_in', 'Trade-in'), ('cryptocurrency', 'Cryptocurrency'), ('paypal', 'PayPal'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('samsung_pay', 'Samsung Pay'), ('venmo', 'Venmo'), ('zelle', 'Zelle'), ('wire_transfer', 'Wire Transfer'), ('money_order', 'Money Order'), ('cashiers_check', "Cashier's Check"), ('certified_check', 'Certified Check'), ('personal_check', 'Personal Check'), ('business_check', 'Business Check'), ('cash_equivalent', 'Cash Equivalent'), ('other', 'Other')], max_length=20, null=True, verbose_name='sale payment method'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='sale price'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_price_taxes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='sale price taxes'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_vehicles', to='manager.person', verbose_name='seller'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('purchased', 'Purchased'), ('ready_for_sale', 'Ready for Sale'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('inactive', 'Inactive')], max_length=20, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('pickup', 'Pickup Truck'), ('van', 'Van'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('trailer', 'Trailer'), ('heavy_truck', 'Heavy Truck'), ('delivery_van', 'Delivery Van'), ('taxi', 'Taxi'), ('limousine', 'Limousine')], max_length=20, null=True, verbose_name='vehicle type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_construction',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='year of construction'),
        ),
    ]
