# Generated by Django 5.2.7 on 2025-10-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0023_alter_branch_address_alter_branch_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/businesses/', verbose_name='logo'),
        ),
    ]
