# Generated by Django 5.2.7 on 2025-10-18 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_business', to='manager.business', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='person',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_business', to='manager.business', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_business', to='manager.business', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_branch', to='manager.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_business', to='manager.business', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='buy price'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='buy_price_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='buy price taxes'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_buyer_person', to='manager.person', verbose_name='buyer'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='sale price'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_price_taxes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='sale price taxes'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_seller_person', to='manager.person', verbose_name='seller'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='internal id')),
                ('method', models.CharField(blank=True, max_length=20, null=True, verbose_name='method')),
                ('date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('information', models.TextField(blank=True, null=True, verbose_name='information')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='amount')),
                ('from_or_to', models.CharField(blank=True, max_length=20, null=True, verbose_name='from/to')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='date time')),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='tax')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='category')),
                ('subcategory', models.CharField(blank=True, max_length=20, null=True, verbose_name='subcategory')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_business', to='manager.business', verbose_name='business')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_vehicle', to='manager.vehicle', verbose_name='business')),
            ],
            options={
                'ordering': ['business', 'internal_id'],
                'unique_together': {('business', 'internal_id')},
            },
        ),
    ]
