# Generated by Django 5.2.7 on 2025-10-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_alter_branch_business_alter_person_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_branches', to='manager.business', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='person',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_persons', to='manager.business', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_transactions', to='manager.business', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_transactions', to='manager.vehicle', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='user',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_users', to='manager.business', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_vehicles', to='manager.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_vehicles', to='manager.business', verbose_name='business'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_person_vehicles', to='manager.person', verbose_name='buyer'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_person_vehicles', to='manager.person', verbose_name='seller'),
        ),
    ]
