# Generated by Django 5.2.7 on 2025-10-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0026_alter_branch_business_alter_person_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.CharField(blank=True, null=True, verbose_name='date time'),
        ),
    ]
