# Generated by Django 5.2.7 on 2025-10-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0027_alter_transaction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date time'),
        ),
    ]
