# Generated by Django 5.2.7 on 2025-10-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0029_alter_transaction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('car_purchase', 'Car Purchase'), ('advance_payment', 'Advance Payment'), ('legal_costs', 'Legal Costs'), ('car_sale', 'Car Sale'), ('bank', 'Bank'), ('contributions', 'Contributions'), ('entertainment', 'Entertainment'), ('office', 'Office'), ('loan', 'Loan'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('vehicles', 'Vehicles'), ('financing', 'Financing'), ('court_costs', 'Court Costs'), ('price_reduction', 'Price Reduction'), ('deposit_bond', 'Deposit Bond'), ('wages_salaries', 'Wages Salaries'), ('rent_utilities', 'Rent Utilities'), ('private_transfer', 'Private Transfer'), ('commission', 'Commission'), ('invoice', 'Invoice'), ('donation', 'Donation'), ('tax_consultant', 'Tax Consultant'), ('taxes', 'Taxes'), ('phone_communication', 'Phone Communication'), ('insurance', 'Insurance'), ('advertising', 'Advertising'), ('other_fees', 'Other Fees'), ('unknown', 'Unknown')], max_length=20, null=True, verbose_name='category'),
        ),
    ]
