# Generated by Django 5.2.7 on 2025-10-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0030_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'Complete'), ('missing_details', 'Missing Details'), ('inactive', 'Inactive')], max_length=20, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='doors',
            field=models.CharField(blank=True, choices=[('2', '2 Doors'), ('3', '3 Doors'), ('4', '4 Doors'), ('5', '5 Doors'), ('6', '6 Doors'), ('other', 'Other')], null=True, verbose_name='doors'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('gasoline', 'Gasoline/Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('lpg', 'LPG (Liquid Petroleum Gas)'), ('cng', 'CNG (Compressed Natural Gas)'), ('ethanol', 'Ethanol'), ('hydrogen', 'Hydrogen'), ('other', 'Other')], max_length=20, null=True, verbose_name='fuel type'),
        ),
    ]
