# Generated by Django 5.2.7 on 2025-10-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0031_transaction_status_alter_vehicle_doors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='internal_comments',
            field=models.TextField(blank=True, null=True, verbose_name='internal comments'),
        ),
    ]
