# Generated by Django 5.2.7 on 2025-10-20 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0034_alter_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_or_to',
            field=models.CharField(blank=True, null=True, verbose_name='from/to'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'Complete'), ('review_required', 'Review required'), ('inactive', 'Inactive')], max_length=20, null=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_transactions', to='manager.vehicle', verbose_name='Vehicle'),
        ),
    ]
