# Generated by Django 5.2.7 on 2025-10-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0035_alter_transaction_from_or_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('confirmed', 'Confirmed'), ('review_required', 'Review required'), ('inactive', 'Inactive')], max_length=20, null=True, verbose_name='status'),
        ),
    ]
