# Generated by Django 5.2.7 on 2025-10-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0036_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('volksbank', 'Volksbank'), ('sparkasse', 'Sparkasse'), ('other', 'Other')], max_length=20, null=True, verbose_name='method'),
        ),
    ]
