# Generated by Django 5.2.7 on 2025-10-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0037_alter_transaction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transactions_access',
            field=models.BooleanField(default=False, verbose_name='transactions access'),
        ),
    ]
