# Generated by Django 5.2.7 on 2025-10-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0038_user_transactions_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='backup email address'),
        ),
    ]
