# Generated by Django 5.2.7 on 2025-10-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0039_user_backup_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='accident_vehicle',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('accident', 'Accident'), ('damage', 'Damage')], max_length=20, null=True, verbose_name='damage type'),
        ),
    ]
