# Generated by Django 5.2.7 on 2025-10-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0040_remove_vehicle_accident_vehicle_vehicle_damage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='internal_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='internal id'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('business', 'internal_id')},
        ),
    ]
