# Generated by Django 5.2.7 on 2025-11-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0042_alter_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('accident', 'Accident'), ('damage', 'Damage'), ('undamaged', 'Undamaged')], max_length=20, null=True, verbose_name='damage type'),
        ),
    ]
