# Generated by Django 5.2.7 on 2025-11-04 22:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0043_alter_vehicle_damage_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='street'),
        ),
        migrations.AddField(
            model_name='person',
            name='address_street_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='street number'),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='active', max_length=100, verbose_name='status'),
        ),
    ]
