# Generated by Django 5.2.7 on 2025-11-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0044_alter_person_options_remove_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_buyer',
            field=models.BooleanField(default=False, verbose_name='is buyer'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='is seller'),
        ),
    ]
