# Generated by Django 5.2.7 on 2025-11-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0045_person_is_buyer_person_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_seller',
        ),
    ]
