# Generated by Django 5.2.7 on 2025-11-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0046_remove_person_is_buyer_remove_person_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='sale_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='sale commission'),
        ),
    ]
