# Generated by Django 5.2.7 on 2026-01-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0047_vehicle_sale_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address_city',
            field=models.CharField(default='temp_city', max_length=100, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='address_country',
            field=models.CharField(default='temp_country', max_length=100, verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='address_postal_code',
            field=models.CharField(default=666666, max_length=20, verbose_name='postal code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='address_street',
            field=models.CharField(default='temp_street', max_length=200, verbose_name='street'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='address_street_number',
            field=models.PositiveIntegerField(default=66, verbose_name='street number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='internal_id',
            field=models.PositiveIntegerField(default=666, verbose_name='internal id'),
            preserve_default=False,
        ),
    ]
