# Generated by Django 5.2.7 on 2026-01-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0049_alter_person_options_remove_person_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='business',
            name='address_country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='business',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code'),
        ),
        migrations.AddField(
            model_name='business',
            name='address_street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='street'),
        ),
        migrations.AddField(
            model_name='business',
            name='address_street_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='street number'),
        ),
        migrations.AddField(
            model_name='business',
            name='bank_bic_swift',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='BIC/SWIFT'),
        ),
        migrations.AddField(
            model_name='business',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='business',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='bank name'),
        ),
        migrations.AddField(
            model_name='business',
            name='court_district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='court district'),
        ),
        migrations.AddField(
            model_name='business',
            name='court_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='court registration number'),
        ),
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='business',
            name='eori_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='EORI number'),
        ),
        migrations.AddField(
            model_name='business',
            name='fax_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='fax number'),
        ),
        migrations.AddField(
            model_name='business',
            name='headquarters_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='headquarters city'),
        ),
        migrations.AddField(
            model_name='business',
            name='managing_director',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='managing director'),
        ),
        migrations.AddField(
            model_name='business',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='tax ID'),
        ),
        migrations.AddField(
            model_name='business',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='telephone number'),
        ),
        migrations.AddField(
            model_name='business',
            name='ust_id_nr',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='USt-IdNr'),
        ),
    ]
