# Generated by Django 5.2.7 on 2026-01-05 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0050_business_address_city_business_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legal_entities_access',
            field=models.BooleanField(default=False, verbose_name='legal entities access'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='manufacturer model'),
        ),
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_types', to='manager.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'Body Type',
                'verbose_name_plural': 'Body Types',
                'ordering': ['name'],
                'unique_together': {('name', 'business')},
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='manager.bodytype', verbose_name='body type'),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='manager.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ['name'],
                'unique_together': {('name', 'business')},
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='manager.color', verbose_name='color'),
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_types', to='manager.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'Damage Type',
                'verbose_name_plural': 'Damage Types',
                'ordering': ['name'],
                'unique_together': {('name', 'business')},
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='damage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='manager.damagetype', verbose_name='damage type'),
        ),
        migrations.CreateModel(
            name='DoorsChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors_choices', to='manager.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'Door Option',
                'verbose_name_plural': 'Door Options',
                'ordering': ['name'],
                'unique_together': {('name', 'business')},
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='doors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='manager.doorschoice', verbose_name='doors'),
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_types', to='manager.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'Fuel Type',
                'verbose_name_plural': 'Fuel Types',
                'ordering': ['name'],
                'unique_together': {('name', 'business')},
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='manager.fueltype', verbose_name='fuel type'),
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.PositiveIntegerField(verbose_name='internal id')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('address_street', models.CharField(max_length=200, verbose_name='street')),
                ('address_street_number', models.PositiveIntegerField(verbose_name='street number')),
                ('address_postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('address_city', models.CharField(max_length=100, verbose_name='city')),
                ('address_country', models.CharField(max_length=100, verbose_name='country')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=100, verbose_name='status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20, verbose_name='type')),
                ('tax_identification_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='tax identification number')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_legal_entities', to='manager.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'Legal Entity',
                'verbose_name_plural': 'Legal Entities',
                'ordering': ['name'],
                'unique_together': {('business', 'internal_id')},
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_vehicles', to='manager.legalentity', verbose_name='buyer'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_vehicles', to='manager.legalentity', verbose_name='seller'),
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='manager.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ['name'],
                'unique_together': {('name', 'business')},
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='manager.manufacturer', verbose_name='manufacturer'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='manager.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['name'],
                'unique_together': {('name', 'business')},
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='buy_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_vehicles', to='manager.paymentmethod', verbose_name='buy payment method'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_vehicles', to='manager.paymentmethod', verbose_name='sale payment method'),
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='manager.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['name'],
                'unique_together': {('name', 'business')},
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='manager.vehicletype', verbose_name='vehicle type'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
