# Generated by Django 5.2.7 on 2026-01-05 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0051_user_legal_entities_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='buy_price_taxes',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='sale_price_taxes',
        ),
        migrations.CreateModel(
            name='TaxPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, help_text='Tax percentage value (e.g., 16.00 for 16%)', max_digits=5, verbose_name='percentage')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_no_tax', models.BooleanField(default=False, help_text='Check this for the "No Tax" option to enable special handling', verbose_name='is no tax')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_percentages', to='manager.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'Tax Percentage',
                'verbose_name_plural': 'Tax Percentages',
                'ordering': ['percentage', 'name'],
                'unique_together': {('name', 'business')},
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='buy_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_vehicles', to='manager.taxpercentage', verbose_name='buy tax'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sale_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_vehicles', to='manager.taxpercentage', verbose_name='sale tax'),
        ),
        migrations.CreateModel(
            name='ManufacturerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_models', to='manager.business', verbose_name='business')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='manager.manufacturer', verbose_name='manufacturer')),
            ],
            options={
                'verbose_name': 'Manufacturer Model',
                'verbose_name_plural': 'Manufacturer Models',
                'ordering': ['name'],
                'unique_together': {('name', 'manufacturer', 'business')},
            },
        ),
    ]
