# Generated by Django 5.2.7 on 2026-01-08 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0056_loginrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='request ID')),
                ('approval_token', models.CharField(max_length=64, unique=True, verbose_name='approval token')),
                ('action_type', models.CharField(choices=[('employee_login', 'Employee Login'), ('manager_login', 'Manager Login'), ('password_reset', 'Password Reset'), ('verify_email', 'Verify Email')], default='manager_login', max_length=20, verbose_name='action type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('used', 'Used')], default='pending', max_length=20, verbose_name='status')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_requests', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Auth Action Request',
                'verbose_name_plural': 'Auth Action Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='LoginRequest',
        ),
    ]
