# Generated by Django 5.2.7 on 2026-01-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0057_authactionrequest_delete_loginrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authactionrequest',
            name='action_type',
            field=models.CharField(choices=[('employee_login', 'Employee Login'), ('manager_login', 'Manager Login'), ('password_reset', 'Password Reset'), ('verify_email', 'Verify Email'), ('confirm_email', 'Confirm Email')], default='manager_login', max_length=20, verbose_name='action type'),
        ),
        migrations.AlterField(
            model_name='authactionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('used', 'Used'), ('waiting_for_new_email', 'Waiting for New Email')], default='pending', max_length=25, verbose_name='status'),
        ),
    ]
