# Generated by Django 5.2.7 on 2026-01-16 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0058_alter_authactionrequest_action_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change')], max_length=20, verbose_name='action')),
                ('entity_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('transaction', 'Transaction'), ('legal_entity', 'Legal Entity'), ('user', 'User'), ('business_settings', 'Business Settings'), ('choice', 'Choice')], max_length=30, verbose_name='entity type')),
                ('entity_id', models.PositiveIntegerField(blank=True, help_text='Internal ID of the affected entity', null=True, verbose_name='entity ID')),
                ('entity_name', models.CharField(blank=True, help_text='Display name for the entity (e.g., "BMW X5", "Transaction #123")', max_length=200, verbose_name='entity name')),
                ('details', models.TextField(blank=True, help_text='Additional details about the action', verbose_name='details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='manager.business', verbose_name='business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
