# Generated by Django 5.2.7 on 2026-04-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0061_rename_manufacturer_to_make_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authactionrequest',
            name='action_type',
            field=models.CharField(choices=[('employee_login', 'Employee Login'), ('manager_login', 'Manager Login'), ('password_reset', 'Password Reset'), ('verify_email', 'Verify Email'), ('confirm_email', 'Confirm Email'), ('password_change', 'Password Change'), ('email_change_verify_old', 'Email Change - Verify Old'), ('email_change_verify_new', 'Email Change - Verify New'), ('backup_email_verify_official', 'Backup Email - Verify Official'), ('backup_email_verify_new', 'Backup Email - Verify New'), ('register_verify_email', 'Register - Verify Email'), ('register_verify_backup', 'Register - Verify Backup'), ('admin_activate', 'Admin Activate Account')], default='manager_login', max_length=40, verbose_name='action type'),
        ),
        migrations.AlterField(
            model_name='authactionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('used', 'Used'), ('waiting_for_new_email', 'Waiting for New Email'), ('waiting_for_backup_email', 'Waiting for Backup Email'), ('waiting_for_admin', 'Waiting for Admin')], default='pending', max_length=25, verbose_name='status'),
        ),
    ]
