# Generated by Django 5.2.7 on 2026-05-03 04:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0062_extend_auth_action_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='target_annual_return',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='target annual return (%)'),
        ),
        migrations.AddField(
            model_name='business',
            name='target_days_on_stock',
            field=models.PositiveIntegerField(default=45, verbose_name='target days on stock'),
        ),
    ]
