# Generated by Django 5.2.7 on 2026-05-16 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0063_business_target_annual_return_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='key number')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_numbers', to='manager.business', verbose_name='business')),
                ('vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_number', to='manager.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'Key Number',
                'verbose_name_plural': 'Key Numbers',
                'ordering': ['number'],
                'unique_together': {('number', 'business')},
            },
        ),
    ]
