# Generated by Django 5.2.7 on 2026-05-16 23:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0064_keynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity_viewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Tracks when the user last opened the notifications dropdown.', verbose_name='last activity viewed at'),
        ),
    ]
