# Generated by Django 5.2.7 on 2026-05-27 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0065_user_last_activity_viewed_at'),
    ]

    operations = [
    ]
