# Generated by Django 5.2.7 on 2026-05-27 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0065_user_last_activity_viewed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='city')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='manager.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'manager_city',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='legalentity',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_entities', to='manager.city', verbose_name='city'),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='country')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='manager.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'manager_country',
                'ordering': ['name'],
                'unique_together': {('name', 'business')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='manager.country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='legalentity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_entities', to='manager.country', verbose_name='country'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country', 'business')},
        ),
    ]
