# Generated by Django 5.2.7 on 2026-05-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0066_city_alter_legalentity_address_city_country_and_more'),
    ]

    operations = [
    ]
