# Generated by Django 5.2.7 on 2026-05-27 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0066_city_legalentity_city_country_city_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalentity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='country',
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='address_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_entities', to='manager.city', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='address_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_entities', to='manager.country', verbose_name='country'),
        ),
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
        migrations.AlterModelTable(
            name='country',
            table=None,
        ),
    ]
