# Generated by Django 5.2.7 on 2026-08-14 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0067_remove_legalentity_city_remove_legalentity_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='sale_commission',
        ),
        migrations.CreateModel(
            name='VehicleExpenseEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('earning', 'Earning')], max_length=10, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_expenses_earnings', to='manager.business', verbose_name='business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_expenses_earnings', to='manager.category', verbose_name='category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_expenses_earnings', to='manager.subcategory', verbose_name='subcategory')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_earnings', to='manager.vehicle', verbose_name='vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
